controller_manager:
  ros__parameters:
    update_rate: 400
    use_sim_time: true

    joint_state_broadcaster:
      type:   joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

velocity_controller:
  ros__parameter:
    joints:
      -base_to_disk
    
    state_interfaces:
      -position
      -velocity

